[sharepoint]
USERNAME = "washington.gouvea@synvia.com"
PASSWORD = "vwthcktbjrwrqpqy"
ARQUIVO = "/personal/washington_gouvea_synvia_com/Documents/Data Analysis/Inspecao Garantia da Qualidade/documentos_arquivo.xlsx"
SITE_BASE = "https://synviagroup-my.sharepoint.com/personal/washington_gouvea_synvia_com"
SOLICITAÇÕES = "/personal/washington_gouvea_synvia_com/Documents/Solicitações - Arquivamento_Desarquivamento GQ.xlsx"